# Site settings
title: Emotions in Conflicts
tag_text: Emotions in Conflicts
description: Let’s get emotional, we already got physical..
url: "https://matterhorn-ada.github.io/"
baseurl: "https://matterhorn-ada.github.io/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
